### ISSUE TITLE
Execution fails on mac

### ISSUE THREAD

**Issue by joaocc** [bspaans/kubefuse#24]
* macOS Sierra 10.12.6
* Python 3.6.4

install looks ok
```
$ pip3 install kubefuse
Collecting kubefuse
  Downloading kubefuse-0.7.3.tar.gz
Requirement already satisfied: fusepy>=2.0.4 in /usr/local/lib/python3.6/site-packages (from kubefuse)
Collecting python-myna==1.2.0 (from kubefuse)
  Downloading python-myna-1.2.0.tar.gz
Requirement already satisfied: PyYAML>=3 in /usr/local/lib/python3.6/site-packages (from kubefuse)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/site-packages (from kubefuse)
Building wheels for collected packages: kubefuse, python-myna
  Running setup.py bdist_wheel for kubefuse ... done
  Stored in directory: /Users/my-user/Library/Caches/pip/wheels/92/18/07/49c7dbbc561c8ac4e366befec2af409f53765662ae4d4081bc
  Running setup.py bdist_wheel for python-myna ... done
  Stored in directory: /Users/my-user/Library/Caches/pip/wheels/d3/f5/6f/fd9f2b7ffc199ec6363b413a4a14e7dca1d4766ea42565b8a3
Successfully built kubefuse python-myna
Installing collected packages: python-myna, kubefuse
Successfully installed kubefuse-0.7.3 python-myna-1.2.0
```

running it not so
```
$ kubefuse
Traceback (most recent call last):
  File "/usr/local/bin/kubefuse", line 7, in <module>
    from kubefuse.kubefuse import main
  File "/usr/local/lib/python3.6/site-packages/kubefuse/kubefuse.py", line 13
    print "It looks like the Fuse system library is missing."
                                                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "It looks like the Fuse system library is missing.")?
```

**Comment by bspaans** [comment]
Looks like you need to install https://osxfuse.github.io/

**Comment by joaocc** [comment]
I do have it installed (v3.7.1). Any ideas? thx

**Comment by bspaans** [comment]
Not sure, probably some library path issue? I'm not on Mac anymore so can't help you much I'm afraid, but I think I had it working using fuse installed through brew.

**Comment by bspaans** [comment]
Oh actually, just read the error more closely: you are using Python3 and this is Python2 code unfortunately.

**Comment by joaocc** [comment]
ah. ok. i'll try using virtual env. thx!

**Comment by adamgoose** [comment]
Dupe of #25. I only give the newer issue precedence over this one as its more descriptive and indicative of the issue at hand.
